# Generated by Django 3.2.9 on 2021-11-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Registration',
            fields=[
                ('roll_number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('B_Form', models.ImageField(default='', upload_to='B_Form/')),
                ('DOB', models.DateField()),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=30)),
                ('addmission_date', models.DateField()),
                ('promised_fee', models.IntegerField()),
            ],
            options={
                'db_table': 'student_registration',
            },
        ),
    ]
